application: n00bdash
version: main
runtime: go
api_version: go1

default_expiration: "1h"

handlers:
- url: /favicon.ico
  static_files: s/favicon.ico
  upload: s/favicon.ico

- url: /s
  static_dir: s

- url: /.*
  script: _go_app
